#!/bin/bash

#exits if a command fails
set -e
#errors if an variable is referenced before being set
set -u
#shows the commands that get run (mostly for debug)
#set -x

#Function to do cleanup in case of script failure
function egress {
    echo EGRESS
}
trap egress EXIT

###
### Variables (Shared)
###

# MQTT Config
MQTTIP="broker.hivemq.com"
MQTTPORT="1883"

# For example: date +%s | sha256sum | base64 | head -c 16 ; echo
MQTTPREFIX="asdf"
MQTTCOMMANDS="$MQTTPREFIX/commands"
MQTTRESULTS="$MQTTPREFIX/results"

# Preshared Key for encryption over MQTT
SECRETPSK="wtf"

#Logging config
LOGFILE=$0.log
RETAIN_NUM_LINES=100
ENALBE_LOG=true

###
### Variables (Client)
###

# Place to store the keys
CLIENTDIRECTORY="/etc/wireguard/keys"

# Prvate or public endpoint IP
ENDPOINTISPUBLIC=false
ENDPOINTISNATTED=false

# Mesh or Hub and Spoke (Mesh=all hubs)
ENDPOINTISHUB=true

# Routing information
ISDEFAULTROUTE=false
ROUTEMETRIC=111

###
### Variables (Server)
###

SERVERDIRECTORY=$(pwd)
POOLWG="169.254.124.0/16"
POOLV4="172.20.10.0/24"
# get one here https://simpledns.com/private-ipv6
POOLV6="fd20:b765:de64:0d5c::/64"

###
### END Variables
###

# Web status page
/usr/bin/php -S 0.0.0.0:80  > /dev/null 2>&1 &

mqttencrypt(){
    echo $1 | openssl enc -aes-128-cbc -A -base64 -salt -pass pass:$SECRETPSK 2>/dev/null
}

mqttdecrypt(){
    echo $1 | openssl enc -aes-128-cbc -a -d -salt -pass pass:$SECRETPSK 2>/dev/null
}

#Shutting down the service cleanly
if [ "$1" = stop ]; then
    echo "Stopping!"
    echo $(mqttencrypt "{\"msgtype\":\"anounce\",\"command\":\"del_peer\",\"pubkey\":\"$(cat /etc/wireguard/keys/server.pub)\"}") | mosquitto_pub --stdin-line -h $MQTTIP -p $MQTTPORT -t $MQTTRESULTS
    STATICROUTES=$(wg show | grep endpoint | awk '{print $2}' | cut -d: -f1)
    ENDPOINTIF=$(ip -o route get to 8.8.8.8 |  awk '{print $5;}')
    LOCALDEFAULTROUTE=$(ip route | awk '/default/ { print $3 }')

    if ip link show wg0 > /dev/null 2>&1; then
        ip link delete dev wg0
    fi
    if ip link show wg0vxlan > /dev/null 2>&1; then
        ip link delete dev wg0vxlan
    fi

    for r in $STATICROUTES
    do
      ip route del $r via $LOCALDEFAULTROUTE
    done

    if iptables -C POSTROUTING -t nat -o $ENDPOINTIF -j MASQUERADE > /dev/null 2>&1 ; then
      iptables -t nat -D POSTROUTING -o $ENDPOINTIF -j MASQUERADE
    fi
    if iptables -C FORWARD -i wg0vxlan -j ACCEPT > /dev/null 2>&1 ; then
      iptables -D FORWARD -i wg0vxlan -j ACCEPT
    fi
    if iptables -C FORWARD -o wg0vxlan -j ACCEPT > /dev/null 2>&1 ; then
      iptables -D FORWARD -o wg0vxlan -j ACCEPT


fi
    exit 0
fi

# Setup logging functions
function logsetup {
    TMP=$(tail -n $RETAIN_NUM_LINES $LOGFILE 2>/dev/null) && echo "${TMP}" > $LOGFILE
    exec > >(tee -a $LOGFILE)
    exec 2>&1
}

function log {
    echo -e "\e[1;31m[$(date --rfc-3339=seconds)]: $*\e[0m"
}

if [ "$ENALBE_LOG" = true ] ; then
    logsetup
fi

is_valid_ipv4() {
  local -a octets=( ${1//\./ } )
  local RETURNVALUE=0

  # return an error if the IP doesn't have exactly 4 octets
  [[ ${#octets[@]} -ne 4 ]] && return 1

  for octet in ${octets[@]}
  do
    if [[ ${octet} =~ ^[0-9]{1,3}$ ]]
    then # shift number by 8 bits, anything larger than 255 will be > 0
      ((RETURNVALUE += octet>>8 ))
    else # octet wasn't numeric, return error
      return 1
    fi
  done
  return ${RETURNVALUE}
}

getnet() {
    IP=$1
    PREFIX=$2
    IFS=. read -r i1 i2 i3 i4 <<< $IP
    D2B=({0..1}{0..1}{0..1}{0..1}{0..1}{0..1}{0..1}{0..1})
    binIP=${D2B[$i1]}${D2B[$i2]}${D2B[$i3]}${D2B[$i4]}
    binIP0=${binIP::$PREFIX}$(printf '0%.0s' $(seq 1 $((32-$PREFIX))))
    echo $((2#${binIP0::8})).$((2#${binIP0:8:8})).$((2#${binIP0:16:8})).$((2#${binIP0:24:8}))/$2
}

getip() {
    ip addr show $1 | grep -Po 'inet \K[\d.]+'
}

getcidr() {
    ip addr show $1 | grep -Po 'inet [\d.]+\/\K[\d.]+'
}

nextip(){
    IP=$1
    IP_HEX=$(printf '%.2X%.2X%.2X%.2X\n' `echo $IP | sed -e 's/\./ /g'`)
    NEXT_IP_HEX=$(printf %.8X `echo $(( 0x$IP_HEX + 1 ))`)
    NEXT_IP=$(printf '%d.%d.%d.%d\n' `echo $NEXT_IP_HEX | sed -r 's/(..)/0x\1 /g'`)
    echo "$NEXT_IP"
}

mac_to_ipv6_ll() {
    IFS=':'; set $1; unset IFS
    echo "$(echo $POOLV6 | cut -d/ -f1)$(printf %02x $((0x$1 ^ 2)))$2:${3}$4:$5$6"
}

function json_extract() {
  local key=$1
  local json=$2

  local string_regex='"([^"\]|\\.)*"'
  local number_regex='-?(0|[1-9][0-9]*)(\.[0-9]+)?([eE][+-]?[0-9]+)?'
  local value_regex="${string_regex}|${number_regex}|true|false|null"
  local pair_regex="\"${key}\"[[:space:]]*:[[:space:]]*(${value_regex})"

  if [[ ${json} =~ ${pair_regex} ]]; then
    echo $(sed 's/^"\|"$//g' <<< "${BASH_REMATCH[1]}")
  else
    return 0
  fi
}


##
### START OF CLIENT
##
if [ "$1" = client ]; then

# Check if run as root
if [[ $UID -ne 0 ]]; then
    echo "This script needs to be run as root (with sudo)."
    exit 1
fi

#Get local bridge networks for babel redistribution
#myinterfaces=$(ip link show type bridge | grep  '^[0-9]' | awk '{print $2}' | cut -d: -f1)
ENDPOINTIF=$(ip -o route get to 8.8.8.8 |  awk '{print $5;}')
#myinterfaces=$(ip link show | grep '^[0-9]' | awk '{print $2}' | cut -d: -f1 | grep -v -e "lo" -e "wg0" -e "$ENDPOINTIF")

if ip link show | grep '^[0-9]' | awk '{print $2}' | cut -d: -f1 | grep -v -e "lo" -e "wg0" -e "$ENDPOINTIF" > /dev/null 2>&1; then
    log "Already have wg0. Deleting..."
    myinterfaces=$(ip link show | grep  '^[0-9]' | awk '{print $2}' | cut -d: -f1 | grep -v -e "lo" -e "wg0" -e "$ENDPOINTIF")
else
    myinterfaces=""
fi

echo "keep-unfeasible true" > babel.conf
echo "default wired true split-horizon true" >> babel.conf
echo "random-id true" >> babel.conf
echo "local-port 33123" >> babel.conf
echo "interface wg0vxlan" >> babel.conf
if [ ! ${#myinterfaces} = 0 ]; then
    while read -r line; do
        if  is_valid_ipv4 "$(getip $line)" ; then
            echo "redistribute ip $(getnet $(getip $line) $(getcidr $line))" >> babel.conf
        else
            log "Babeld - Ignoring interface $line"
        fi
    done <<< "$myinterfaces"
fi

#Startup
if [ ! -d "$CLIENTDIRECTORY" ]; then
    # Control will enter here if $CLIENTDIRECTORY doesn't exist.
    log "Config Dir not found. Creating and making new keys."
    mkdir -p /etc/wireguard/keys
    chmod 700 /etc/wireguard/keys
    touch /etc/wireguard/keys/server
    chmod 600 /etc/wireguard/keys/server
    wg genkey > /etc/wireguard/keys/server
    wg pubkey < /etc/wireguard/keys/server > /etc/wireguard/keys/server.pub
elif [ -d "$CLIENTDIRECTORY" ]; then
    log "Config Dir found."
    #check if keys exist.
    if [ ! -f "$CLIENTDIRECTORY/server" ]; then
        log "No Key found. Generating new pair"
        touch /etc/wireguard/keys/server
        chmod 600 /etc/wireguard/keys/server
        wg genkey > /etc/wireguard/keys/server
        wg pubkey < /etc/wireguard/keys/server > /etc/wireguard/keys/server.pub
    fi
fi

#Grab correct local interface IP for peers to connect to
if [ "$ENDPOINTISPUBLIC" = false ]; then
    ENDPOINTIP=$(ip -o route get to 8.8.8.8 | sed -n 's/.*src \([0-9.]\+\).*/\1/p')
else
    ENDPOINTIP=$(curl http://checkip.amazonaws.com)
fi

#Grab interface name for iptables natting
if [ "$ISDEFAULTROUTE" = true ]; then
    ENDPOINTIF=$(ip -o route get to 8.8.8.8 |  awk '{print $5;}')
fi

#Get the local default gateway
LOCALDEFAULTROUTE=$(ip route | awk '/default/ { print $3 }')

#Anounce startup to server
PUBKEY=$(cat /etc/wireguard/keys/server.pub)
if [ "$ENDPOINTISNATTED" = false ]; then
    log "Announcing: $PUBKEY $ENDPOINTIP"
    echo $(mqttencrypt "{\"pubkey\":\"$PUBKEY\",\"hostname\":\"$(cat /etc/hostname)\",\"endpointip\":\"$ENDPOINTIP\",\"ishub\":\"$ENDPOINTISHUB\"}") | mosquitto_pub --stdin-line -q 1 -h $MQTTIP -p $MQTTPORT -t $MQTTRESULTS
    log "Sending {\"pubkey\":\"$PUBKEY\",\"hostname\":\"$(cat /etc/hostname)\",\"endpointip\":\"$ENDPOINTIP\",\"ishub\":\"$ENDPOINTISHUB\"}"
else
    log "Announcing: $PUBKEY"
    echo $(mqttencrypt "{\"pubkey\":\"$PUBKEY\",\"hostname\":\"$(cat /etc/hostname)\",\"endpointip\":\"behindnat\",\"ishub\":\"$ENDPOINTISHUB\"}") | mosquitto_pub --stdin-line -q 1 -h $MQTTIP -p $MQTTPORT -t $MQTTRESULTS
    log "Sending {\"pubkey\":\"$PUBKEY\",\"hostname\":\"$(cat /etc/hostname)\",\"endpointip\":\"behindnat\",\"ishub\":\"$ENDPOINTISHUB\"}"
fi

#Background Loop for Anounce CMD messages
while /bin/true; do
    mosquitto_sub -h $MQTTIP -p $MQTTPORT -t $MQTTCOMMANDS |
    while IFS= read -r encline; do
    #log "Received MQTT CMD Message: $encline"
    line=$(mqttdecrypt $encline)
    log "Received MQTT CMD Message: $line"

    msgtype=$(json_extract msgtype $line)
    command=$(json_extract command $line)
    recpubkey=$(json_extract pubkey $line)
    endpointip=$(json_extract endpointip $line)
    allowedips=$(json_extract allowedips $line)
    recendpointishub=$(json_extract ishub $line)
    #log "Received CMD Command: $msgtype $command $recpubkey $endpointip $allowedips"

    if [ $msgtype = "anounce" ]; then
        if [ $command = "add_peer" ] && [ ! $recpubkey = $PUBKEY ]; then
            if [ "$ENDPOINTISHUB" = "true" ] || [ "$recendpointishub" = "true" ]; then 
                bridge fdb append 00:00:00:00:00:00 dev wg0vxlan dst $allowedips via wg0
                if [ $endpointip = "behindnat" ]; then
                    wg set wg0 peer $recpubkey allowed-ips $allowedips/32
                    log "Adding new Peer $recpubkey WITHOUT endpoint"
                else
                    wg set wg0 peer $recpubkey allowed-ips $allowedips/32 endpoint $endpointip:51820
                    log "Adding new Peer $recpubkey at $endpointip:51820"
                      if [ $(ip route show | grep -co $endpointip ) = 0 ]; then
                        ip route add $endpointip via $LOCALDEFAULTROUTE
                      fi
                fi
            fi
        elif [ $command = "del_peer" ] && [ ! $recpubkey = $PUBKEY ]; then
                PEERIP=$(wg | grep -A 1 $recpubkey | tail -n 1 | awk '{print $2}' | cut -d: -f1)
                if [ ! $PEERIP = '' ] ; then
                  wg set wg0 peer $recpubkey remove
                  if [ ! $(ip route show | grep -co $PEERIP) = 0 ] ; then
                    ip route del $endpointip via $LOCALDEFAULTROUTE
                  fi
                fi
                log "Removing peer $recpubkey"
        fi
    fi
    done
done & #This loop runs in background
#Finnish Anounce loop


# MAIN LOOP
mqttpeer=$MQTTCOMMANDS$( echo $PUBKEY | base64 | cut -c1-16 )
log "$mqttpeer"

mosquitto_sub -c -i $mqttpeer -q 1 -h $MQTTIP  -p $MQTTPORT -t $mqttpeer |
while IFS= read -r encline
    #log "Received MQTT Message: $encline"
    line=$(mqttdecrypt $encline)
    log "Received MQTT Message: $line"

    msgtype=$(json_extract msgtype $line)
    command=$(json_extract command $line)
    recpubkey=$(json_extract pubkey $line)
    endpointip=$(json_extract endpointip $line)
    allowedips=$(json_extract allowedips $line)
    wg0ip=$(json_extract wg0ip $line)
    wg0vxlanip=$(json_extract wg0vxlanip $line)
    wg0vxlanip6=$(json_extract wg0vxlanip6 $line)
    wg0vxlanmac=$(json_extract wg0vxlanmac $line)
    #log "$msgtype $command $recpubkey $endpointip $allowedips $wg0ip $wg0vxlanip $wg0vxlanip6 $wg0vxlanmac"

    do
        RETURNVAL=false
        if [ "$msgtype" = "anounce" ]; then
            if [ $command = "sync_peer" ]; then
                bridge fdb append 00:00:00:00:00:00 dev wg0vxlan dst $allowedips via wg0
                if [ $endpointip = "behindnat" ]; then
                    wg set wg0 peer $recpubkey allowed-ips $allowedips/32
                    log "Adding new Peer $noThree WITHOUT endpoint"
                else
                    wg set wg0 peer $recpubkey allowed-ips $allowedips/32 endpoint $endpointip:51820
                    if [ $(ip route show | grep -co $endpointip ) = 0 ]; then
                      ip route add $endpointip via $LOCALDEFAULTROUTE
                    fi
                    log "Adding new Peer $recpubkey at $endpointip:51820"
                fi
            fi
        elif [ ! $recpubkey = $PUBKEY ]; then
            continue
        else
            if [ "$msgtype" = "direct" ]; then
                if [ $command = "cmd_getip_private" ]; then
                    RETURNVAL=$(ip -o route get to 8.8.8.8 | sed -n 's/.*src \([0-9.]\+\).*/\1/p')
                elif [ $command = "cmd_getip_public" ]; then
                    RETURNVAL=$(curl http://checkip.amazonaws.com)
                elif [ $command = "cmd_config_wg0" ]; then
                    if ip link show wg0 > /dev/null 2>&1; then
                        log "Already have wg0. Deleting..."
                        ip link delete dev wg0
                    fi
                    ip link add wg0 type wireguard
                    ip link set dev wg0 mtu 2016
                    wg set wg0 listen-port 51820 private-key /etc/wireguard/keys/server
                    ip addr add $wg0ip dev wg0
                    ip link set wg0 up

                    #RETURNVAL=$(ip add show dev wg0)
                    log "New wg0 created"
                elif [ $command = "cmd_config_vxlan" ]; then
                    if ip link show wg0vxlan > /dev/null 2>&1; then
                        log "Deleting vxlan interface"
                        ip link delete dev wg0vxlan
                    fi
                    ip link add wg0vxlan address $wg0vxlanmac mtu 1966 type vxlan id 8425532 dstport 4789 ttl 1 noudpcsum || true
                    ethtool -K wg0vxlan tx off rx off > /dev/null 2>&1
                    sysctl -w net.ipv4.conf.wg0vxlan.accept_redirects=0 net.ipv4.conf.wg0vxlan.send_redirects=0 net.ipv6.conf.wg0vxlan.accept_redirects=0 > /dev/null 2>&1
                    ip address add $wg0vxlanip dev wg0vxlan || true
                    ip address add $wg0vxlanip6 dev wg0vxlan || true
                    ip link set wg0vxlan up
                    log "New Vxlan Interface created."


                    #Fire up Babeld
                    while true; do
                      if ping $(echo $wg0vxlanip | cut -d/ -f1) -c 3 > /dev/null 2>&1  ; then
                        if [ "$ISDEFAULTROUTE" = true ] ; then
                          echo "redistribute ip 0.0.0.0/0 eq 0  metric $ROUTEMETRIC" >> babel.conf
                          echo "redistribute ip ::/0 eq 0 src-prefix $wg0vxlanip6 metric $ROUTEMETRIC" >> babel.conf
                          echo "redistribute local deny" >> babel.conf
                          echo "redistribute deny" >> babel.conf
                          babeld -c babel.conf &

                          sysctl -w net.ipv4.ip_forward=1 net.ipv6.conf.all.forwarding=1 > /dev/null 2>&1
                          if ! iptables -C POSTROUTING -t nat -o $ENDPOINTIF -j MASQUERADE > /dev/null 2>&1 ; then
                            iptables -t nat -A POSTROUTING -o $ENDPOINTIF -j MASQUERADE
                          fi
                          if ! iptables -C FORWARD -i wg0vxlan -j ACCEPT > /dev/null 2>&1 ; then
                            iptables -A FORWARD -i wg0vxlan -j ACCEPT
                          fi
                          if ! iptables -C FORWARD -o wg0vxlan -j ACCEPT > /dev/null 2>&1 ; then
                            iptables -A FORWARD -o wg0vxlan -j ACCEPT
                          fi
                          break
                        else
                          echo "redistribute local deny" >> babel.conf
                          echo "redistribute deny" >> babel.conf
                          babeld -c babel.conf &
                          break
                        fi
                      fi
                    done

                    #RETURNVAL=$(ip add show dev wg0vxlan)
                elif [ $command = "cmd_machine-id" ]; then
                    RETURNVAL="{\"msgtype\":\"direct\",\"machineid\":\"$(cat /etc/machine-id)\"}"
                else
                    Log "Made it to else statement"
                fi
            elif [ "$command" = "stats" ]; then
                log "Returning some stats?"
            fi
        fi

if [ ! "$RETURNVAL" = false ]
then
    echo $(mqttencrypt "$RETURNVAL") | mosquitto_pub --stdin-line -h $MQTTIP -p $MQTTPORT -t $MQTTRESULTS
fi

done
# MAIN LOOP END
fi

##
### END OF CLIENT
##

##
### START OF SERVER
##
if [ "$1" = server ]; then

#Startup

if [ ! -f "$SERVERDIRECTORY/nodes.conf" ]; then
    log "The nodes file does not exist. Making new one"
    touch $SERVERDIRECTORY/nodes.conf
    chmod 600 $SERVERDIRECTORY/nodes.conf
#    echo "peerpubkey endpointip $POOLWG mac-address $POOLV4 $POOLV6 hostname" > $SERVERDIRECTORY/nodes.conf
#       echo "{\"poolwg0\":\"$POOLWG\",\"poolvxlanv4\":\"$POOLV4\",\"poolvxlanv6\":\"$POOLV6\"}"
    echo "{\"pubkey\":\"recpubkey\",\"endpointip\":\"endpointip\",\"wg0ip\":\"$POOLWG\",\"wg0vxlanmac\":\"vxlanmac\",\"wg0vxlanip\":\"$POOLV4\",\"wg0vxlanip6\":\"$POOLV6\",\"hostname\":\"hostname\",\"ishub\":\"nill\"}" > $SERVERDIRECTORY/nodes.conf
fi

# MAIN LOOP
mosquitto_sub -h $MQTTIP -p $MQTTPORT -t $MQTTRESULTS |
while IFS= read -r encline
    log "[+] - New Loop"
    #log "Received MQTT message $encline"
    line=$(mqttdecrypt $encline)
    log "Received MQTT message $line"

    msgtype=$(json_extract msgtype $line)
    command=$(json_extract command $line)
    recpubkey=$(json_extract pubkey $line)
    endpointip=$(json_extract endpointip $line)
    hostname=$(json_extract hostname $line)
    endpointishub=$(json_extract ishub $line)
    mqttpeer=$MQTTCOMMANDS$( echo $recpubkey | base64 | cut -c1-16 )

        #log "$recpubkey $endpointip $hostname $mqttpeer"

    if [ ${#recpubkey} -ne 44 ]; then
        log "[-] - End Loop"
        continue
    fi

    # MORE LATER MAYBE
    if [ "$msgtype" = "anounce" ]; then
        if [ "$command" = "del_peer" ]; then
            log "Delete Peer"
            endpointip=$(json_extract endpointip $(cat $SERVERDIRECTORY/nodes.conf | grep "$recpubkey"))
            echo $(mqttencrypt "{\"msgtype\":\"anounce\",\"command\":\"del_peer\",\"pubkey\":\"$recpubkey\",\"endpointip\":\"$endpointip\"}") | mosquitto_pub --stdin-line -q 1 -h $MQTTIP -p $MQTTPORT -t $MQTTCOMMANDS
            log "Sending: {\"msgtype\":\"anounce\",\"command\":\"del_peer\",\"pubkey\":\"$recpubkey\"}"
            log "[-] - End Loop"
            continue
        fi
    fi

    do
        ISACTIONED=false
        while read FILELINE
        do
            LOCALPEER=$(json_extract pubkey $FILELINE)
            if [ $recpubkey = $LOCALPEER ] && [ "$ISACTIONED" = false ]; then
                log "PEER IS FOUND IN FILE: $LOCALPEER"

                endpointip=$(json_extract endpointip $FILELINE)
                wg0ip=$(json_extract wg0ip $FILELINE)
                wg0vxlanmac=$(json_extract wg0vxlanmac $FILELINE)
                wg0vxlanip=$(json_extract wg0vxlanip $FILELINE)
                wg0vxlanip6=$(json_extract wg0vxlanip6 $FILELINE)
                hostname=$(json_extract hostname $FILELINE)
                endpointishub=$(json_extract ishub $FILELINE)

                echo $(mqttencrypt "{\"msgtype\":\"direct\",\"command\":\"cmd_config_wg0\",\"pubkey\":\"$LOCALPEER\",\"wg0ip\":\"$wg0ip\"}") | mosquitto_pub --stdin-line -q 1 -h $MQTTIP -p $MQTTPORT -t $mqttpeer
                log "Sending wg0 config: $LOCALPEER cmd cmd_config_wg0 $wg0ip"
                echo $(mqttencrypt "{\"msgtype\":\"direct\",\"command\":\"cmd_config_vxlan\",\"wg0vxlanmac\":\"$wg0vxlanmac\",\"wg0vxlanip\":\"$wg0vxlanip\",\"wg0vxlanip6\":\"$wg0vxlanip6\"}") | mosquitto_pub --stdin-line -q 1 -h $MQTTIP -p $MQTTPORT -t $mqttpeer
                log "Sending vxlan config: $LOCALPEER cmd cmd_config_vxlan $wg0vxlanmac $wg0vxlanip $wg0vxlanip6 "

                echo $(mqttencrypt "{\"msgtype\":\"anounce\",\"command\":\"add_peer\",\"allowedips\":\"$(echo $wg0ip | cut -d/ -f1)\",\"pubkey\":\"$recpubkey\",\"endpointip\":\"$endpointip\",\"ishub\":\"$endpointishub\"}") | mosquitto_pub --stdin-line -q 1 -h $MQTTIP -p $MQTTPORT -t $MQTTCOMMANDS
                log "Sending anounce: {\"msgtype\":\"anounce\",\"command\":\"add_peer\",\"allowedips\":\"$(echo $wg0ip | cut -d/ -f1)\",\"pubkey\":\"$recpubkey\",\"endpointip\":\"$endpointip\",\"hostname\":\"$hostname\",\"ishub\":\"$endpointishub\"}"

                ISACTIONED=true
            fi
        done < $SERVERDIRECTORY/nodes.conf

        if [ "$ISACTIONED" = false ] ; then
            # Make new peer
            tag=$( tail -n 1 $SERVERDIRECTORY/nodes.conf )

            wg0ip=$(json_extract wg0ip $tag)
            wg0vxlanip=$(json_extract wg0vxlanip $tag)

            # Calculate new WG IP
            NEWWGIP="$(nextip $(echo $wg0ip | cut -d/ -f1))/$(echo $wg0ip | cut -d/ -f2)"
            log "Assigned new $hostname wg0 IP $NEWWGIP"

            # Calculate new VX IP
            NEWVXIP="$(nextip $(echo $wg0vxlanip | cut -d/ -f1))/$(echo $wg0vxlanip | cut -d/ -f2)"
            log "Assigned new $hostname VxLan IP $NEWVXIP"

            # Make new Mac address
            NEWMAC=$(printf '68:5d:43:%02X:%02X:%02X\n' $[RANDOM%256] $[RANDOM%256] $[RANDOM%256])
            log "Assigned new $hostname mac-address $NEWMAC"

            # Calculate new V6 IP
            NEWVV6IP="$(mac_to_ipv6_ll $NEWMAC)/$(echo $POOLV6 | cut -d/ -f2)"
            log "Assigned new $hostname IPv6 $NEWVV6IP"


            #Send config to peer
            RETURNWG="{\"msgtype\":\"direct\",\"command\":\"cmd_config_wg0\",\"pubkey\":\"$recpubkey\",\"wg0ip\":\"$NEWWGIP\"}"
            echo $(mqttencrypt "$RETURNWG") | mosquitto_pub --stdin-line -q 1 -h $MQTTIP -p $MQTTPORT -t $mqttpeer
            log "Sending wg0 config to peer: $RETURNWG"
            
            RETURNVX="{\"msgtype\":\"direct\",\"command\":\"cmd_config_vxlan\",\"wg0vxlanmac\":\"$NEWMAC\",\"wg0vxlanip\":\"$NEWVXIP\",\"wg0vxlanip6\":\"$(echo $NEWVV6IP | cut -d/ -f1)\",\"pubkey\":\"$recpubkey\",\"endpointip\":\"$endpointip\"}"
            echo $(mqttencrypt "$RETURNVX") | mosquitto_pub --stdin-line -q 1 -h $MQTTIP -p $MQTTPORT -t $mqttpeer
            log "Sending new VxLan config to Peer: $RETURNVX"

            echo $(mqttencrypt "{\"msgtype\":\"anounce\",\"command\":\"add_peer\",\"allowedips\":\"$(echo $NEWWGIP | cut -d/ -f1)\",\"pubkey\":\"$recpubkey\",\"endpointip\":\"$endpointip\",\"ishub\":\"$endpointishub\"}") | mosquitto_pub --stdin-line -q 1 -h $MQTTIP -p $MQTTPORT -t $MQTTCOMMANDS
            log "Sending anounce: {\"msgtype\":\"anounce\",\"command\":\"add_peer\",\"allowedips\":\"$(echo $NEWWGIP | cut -d/ -f1)\",\"pubkey\":\"$recpubkey\",\"endpointip\":\"$endpointip\",\"ishub\":\"$endpointishub\"}"

            echo "{\"pubkey\":\"$recpubkey\",\"endpointip\":\"$endpointip\",\"wg0ip\":\"$NEWWGIP\",\"wg0vxlanmac\":\"$NEWMAC\",\"wg0vxlanip\":\"$NEWVXIP\",\"wg0vxlanip6\":\"$NEWVV6IP\",\"hostname\":\"$hostname\",\"ishub\":\"$endpointishub\"}" >> $SERVERDIRECTORY/nodes.conf
            ISACTIONED=true

        fi

        # Update Peers and bridge tables

        while read FILELINE
        do
            LOCALPEER=$(json_extract pubkey $FILELINE)
            localendpointip=$(json_extract endpointip $FILELINE)
            wg0ip=$(json_extract wg0ip $FILELINE)
            wg0vxlanip=$(json_extract wg0vxlanip $FILELINE)
            wg0vxlanip6=$(json_extract wg0vxlanip6 $FILELINE)
            wg0vxlanmac=$(json_extract wg0vxlanmac $FILELINE)
            localendpointishub=$(json_extract ishub $FILELINE)
            hostname=$(json_extract hostname $FILELINE)

            if [ $localendpointip = "endpointip" ] || [ $localendpointip = "$endpointip" ]; then
                continue
            fi

            if [ "$localendpointishub" = "true" ] || [ "$endpointishub" = "true" ]; then
                echo $(mqttencrypt "{\"msgtype\":\"anounce\",\"command\":\"sync_peer\",\"allowedips\":\"$(echo $wg0ip | cut -d/ -f1)\",\"pubkey\":\"$LOCALPEER\",\"endpointip\":\"$localendpointip\"}") | mosquitto_pub -q 1 --stdin-line -h $MQTTIP -p $MQTTPORT -t $mqttpeer
                log "Sending anounce to $hostname: {\"msgtype\":\"anounce\",\"command\":\"sync_peer\",\"allowedips\":\"$(echo $wg0ip | cut -d/ -f1)\",\"pubkey\":\"$LOCALPEER\",\"endpointip\":\"$localendpointip\"}"
            else
                log "Not syncing peer: {\"pubkey\":\"$LOCALPEER\",\"endpointip\":\"$localendpointip\",\"hostname\":\"$hostname\"}"                  
            fi
        done < $SERVERDIRECTORY/nodes.conf


log "[-] - End Loop"
done
fi
##
### END OF SERVER
##
